openzim/wp1

lucky/lucky/tables.py
lucky/lucky/templates/format.jinja2
lucky/lucky/templates/table.jinja2

Includes changes to the template file to allow for links to the web tool in the table, as well as general refactoring of the table generation code to make it reusable by both global and project tables.

Generate project tables

---

lucky/lucky/tables.py
lucky/lucky/templates/format.jinja2
lucky/lucky/templates/table.jinja2

In testing, I used strings to call the upload_project_table() function, but in reality, the data coming from the database is bytes.

Project names are byte strings

---

docker-compose.yml

I have no idea if I did this right or how to test it.

Attempt to setup a reverse proxy for the web server

---

docker/workers/Dockerfile
docker/workers/start.sh

Better Crontab entries

---

wp1/logic/project.py
wp1/logic/project_test.py

Record logs when adding a new rating, and tests for the same

---

wp1/tables.py
wp1/tables_test.py

Fixes for table formatting issues

---

wp1/logic/move.py

Small test to verify Docker Hub sync works fine again

Small code beautification

---

wp1/api.py
wp1/logic/api/project.py
wp1/logic/api/project_test.py

Add some missing tests. Found a bug while writing them.

Tests for api/project

---

wp1/logic/project.py

Since this cannot be done in parallel, comment it out for now to avoid jobs failing. We will handle it a different way, see #71.

Comment out global articles update for #71

---

wp1/logic/api/project.py
wp1/logic/project.py
wp1/logic/project_test.py

Fix extra category retrieval code and shape of data in test

---

enqueue-global.py
wp1/logic/project.py
wp1/logic/project_test.py
wp1/tables_test.py

Code for updating the global count of projects on the wiki

---

requirements.txt
wp1/api.py
wp1/logic/category.py
wp1/logic/log.py
wp1/logic/move.py
wp1/logic/page.py
wp1/logic/page_test.py
wp1/logic/project.py
wp1/logic/project_test.py
wp1/logic/rating.py
wp1/logic/util.py
wp1/tables.py
wp1/tables_test.py

The PR in #85 moved some of the HERE strings around (''' strings) and so this PR is an attempt to reformat the queries so they are more logical.

Reformat queries

---

wp1/templates/table.jinja2

Fix what was supposed to be a jinja2 comment into actual comment

---

wp1/constants.py
wp1/logs.py
wp1/logs_test.py

Show a "no logs" message if the logs are empty

---

wp1/templates/log_helpers.jinja2

Guard against None values for l_new in logging

---

wp1/logs.py
wp1/tables.py

Add db.pings basically everywhere

---

docker/frontend/Dockerfile
docker/frontend/gzip.conf

Add compression to nginx config for frontend docker image

---

requirements.txt
wp1/web/app.py
wp1/web/templates/index.html.jinja2

This includes installing the minimal flask-gzip plugin and turning it on. Additionally, some fluff has been added to the index page text so that it is large enough to qualify for gzip compression, for verification purposes.

Enable gzip compression for the Flask API server.

---

wp1-frontend/package.json
wp1-frontend/src/App.vue
wp1-frontend/src/components/Stats.vue
wp1-frontend/src/main.js
wp1-frontend/yarn.lock

Also minor tweaks to index style and display of data, just playing around with Vue.

Add Bootstrap dependency

---

setup/schema.sql

Minor tweak to the file, doesn't change anything consequential.

Update schema file to remove cruft

---

wp1-frontend/src/App.vue

Fix replace command for spaces in project id

---

wp1-frontend/package.json
wp1-frontend/src/App.vue
wp1-frontend/src/components/Autocomplete.vue
wp1-frontend/src/components/IndexPage.vue
wp1-frontend/src/components/ProjectPage.vue
wp1-frontend/src/main.js
wp1-frontend/yarn.lock

The main goal of this work is that:
1. The URL updates to a project specific one when the project changes
2. User can bookmark a project specific page and return to it without having to search
3. User can navigate back and forth between consecutive project pages

Frontend routing

---

wp1-frontend/package.json
wp1-frontend/src/components/ProjectTable.vue
wp1-frontend/yarn.lock

Add loading spinner to ProjectTable

---

supervisord.conf
wp1/queues.py
wp1/web/projects.py

Use a separate queue for manual update/upload jobs.
Fixes #173

Separate manual queue

---

wp1-frontend/src/components/UpdatePage.vue
wp1-frontend/src/main.js
wp1/queues.py

Also improve status messages.
Fixes #181.

Cancel polling when navigating away from manual update page. 

---

enqueue-global.py

Fix import error in global update script

---

wp1/models/wp10/rating.py
wp1/models/wp10/rating_test.py
wp1/web/projects.py

Prefix article wikipedia links with namespaces

---

wp1-frontend/src/App.vue

Make the header title an actual link

---

wp1-frontend/src/App.vue
wp1-frontend/src/components/ArticlePage.vue
wp1-frontend/src/components/ProjectTable.vue

Fixes so that visited links look visited.

---

openapi.yml
wp1-frontend/src/components/ArticlePage.vue
wp1/tables.py
wp1/tables_test.py
wp1/web/projects.py
wp1/web/projects_test.py

Put Wikipedia category links in the header of the article listing page

---

openapi.yml
wp1-frontend/src/components/ArticleTable.vue
wp1/web/projects.py

Also display the article indices on the table, and report back which indices are being displayed.

Update Article table for full pagination through all results

---

wp1-frontend/src/components/ArticlePage.vue
wp1-frontend/src/components/ArticleTable.vue
wp1-frontend/src/components/ArticleTablePagination.vue
wp1-frontend/src/main.js

Refactor pagination code for articles into its own component, and include it twice on the top and bottom of the ArticleTable.
Fixes #213

Put pagination on the bottom of the article list page

---

openapi.yml
wp1-frontend/package.json
wp1-frontend/src/components/ArticlePage.vue
wp1-frontend/src/components/ArticleTable.vue
wp1-frontend/src/components/ArticleTablePageSelect.vue
wp1-frontend/yarn.lock
wp1/logic/rating.py
wp1/web/projects.py
wp1/web/projects_test.py

Creates a collapsable "Custom pagination" control on the articles page which allows users to "Show [  ] results starting with page [  ]", where each of those boxes can be filled in with custom values.
This allows users to view up to 500 results per page, and start on any page they like.
Fixes #205

Custom pagination

---

openapi.yml
wp1-frontend/src/cards.scss
wp1-frontend/src/components/ArticleTable.vue
wp1-frontend/src/components/ArticleTablePageSelect.vue
wp1-frontend/src/components/ArticleTableRatingSelect.vue
wp1/tables.py
wp1/web/projects.py
wp1/web/projects_test.py

Allow user to select quality/importance on the article table page

---

wp1-frontend/src/components/ArticlePage.vue
wp1-frontend/src/components/ArticleTablePageSelect.vue

Fix bug with numRows reverting to 100

---

wp1-frontend/src/components/ArticleTable.vue
wp1-frontend/src/components/ArticleTablePageSelect.vue

Fixes #234
Also don't show prev/next when there is no data.

Don't allow for pagination below page 1

---

wp1/web/projects.py

Fix precedence of total page calculation

---

wp1/api_test.py

It was flaky and failing intermittently.

Fix api_test.py

---

.github/workflows/workflow.yml
wp1-frontend/.env.e2e
wp1/credentials.py.e2e

Also re-organize the file so the jobs run in parallel, and delete the .travis.yml configuration file so that Travis CI no longer runs on the project.

Rework Github actions workflow to include Cypress e2e tests

---

.github/workflows/workflow.yml
.gitignore

This should help with debugging.

Upload artifacts from Cypress runs

---

wp1-frontend/package.json
wp1-frontend/yarn.lock

updated cypress to latest version

---

wp1-frontend/yarn.lock

We were getting warnings in our Cypress runs.

Upgrade caniuse-lite

---

wp1-frontend/cypress/.eslintrc.json

In my original Cypress PR, I ignored the Codefactor warnings for undefined symbols because I didn't know how to fix them. These have now been fixed in this PR.

Fix Codefactor for cypress related changes

---

wp1/credentials.py.e2e

@audiodude Updated credential.py.e2e.

updated credentials.py.e2e

---

wp1-frontend/cypress/integration/home_page.spec.js

This resolves a part of #280   
@audiodude @kelson42 I have made cypress for
'When the user selects an item from the dropdown, the appropriate table is displayed'
Please have a look at it so that I can make rest of the tests after your approval.
And what should be done of this CodeFactor issue?

cypress test for project-table

---

wp1-frontend/cypress/integration/article_page.spec.js

@audiodude Added cypress test for "Filtering by article name works".
This resolves a part of #280

Cypress test for filter by article name works

---

wp1-frontend/cypress/integration/article_page.spec.js

Add wait on XHR to article_page spec and reformat file

---

wp1-frontend/cypress/integration/article_page.spec.js
wp1-frontend/cypress/integration/home_page.spec.js

@audiodude Added cypress test for custom pagination.
This resolves a part of #280

cypress test for custom pagination

---

wp1-frontend/src/components/UpdatePage.vue

fixed progress bar visibility issue

---

wp1-frontend/cypress/integration/article_page.spec.js

This is an attempt to fix #317.
It's difficult because the problem doesn't always happen, but hopefully this will help.

Format spec file and add wait for old row to disappear

---

wp1-frontend/cypress.json
wp1-frontend/cypress/integration/article_page.spec.js

@audiodude Added cypress test for correct page being displayed in wikipedia after clicking on first article in the article list.
This resolves a part of #280.

added cypress test for article page in wikipedia

---

wp1-frontend/cypress/integration/article_page.spec.js

@audiodude Added cypress test for widget you mentioned in #280.
This resolves a part of #280.

Cypress test to display articles with selected quality and importance

---

.github/workflows/workflow.yml
.travis.yml
README.md
docker/web/Dockerfile
docker/workers/Dockerfile

@audiodude changed python version to 3.9.4.
This fixes #290.

changed version of python to 3.9.4

---

wp1-frontend/cypress/.eslintrc.json
wp1-frontend/cypress/integration/article_page.spec.js
wp1-frontend/cypress/integration/home_page.spec.js
wp1-frontend/cypress/integration/project_page.spec.js
wp1-frontend/src/cards.scss
wp1-frontend/src/components/ArticleTableNameFilter.vue
wp1-frontend/src/components/ArticleTablePageSelect.vue
wp1-frontend/src/components/ArticleTableRatingSelect.vue
wp1-frontend/src/components/Autocomplete.vue
wp1-frontend/src/components/UpdatePage.vue

@audiodude Sorry for late PR.
This fixed #236

optimization for mobile viewing

---

requirements.txt

Upgrade requests to 2.25.1

---

wp1/credentials.py.example

These keys were introduced in #345 but didn't make it into the production examples until now.

Add new keys to example Production credentials

---

.github/workflows/workflow.yml

Set 2 minute timeout for starting Web backend server in CI

---

wp1-frontend/src/App.vue
wp1-frontend/src/components/ArticlePage.vue
wp1-frontend/src/components/Autocomplete.vue
wp1-frontend/src/components/ComparePage.vue
wp1-frontend/src/components/CreateSimpleList.vue
wp1-frontend/src/components/IndexPage.vue
wp1-frontend/src/components/MyLists.vue
wp1-frontend/src/components/ProjectPage.vue
wp1-frontend/src/components/SecondaryNav.vue
wp1-frontend/src/components/UpdatePage.vue
wp1-frontend/src/main.js

Skeleton of selection pages, with Secondary Nav Bar

---

wp1-frontend/src/components/UpdatePage.vue

@audiodude Added credentials: include to request for manual update 
request which now needs authentication.

added credentials:include to update request

---

wp1/models/wp10/user.py
wp1/web/oauth.py
wp1/web/oauth_test.py
wp10_test.down.sql
wp10_test.up.sql

store users in database

---

README.md
docker-compose.yml

This PR updates the docker-compose.yml file in order to map the production yoyo.ini file to the workers container, and then updates the README to provide instructions for running the migrations from that container.

Run migrations in worker container

---

openapi.yml
wp1/api.py
wp1/web/app.py
wp1/web/sites.py
wp1/web/sites_test.py

This fixes #366 
I will create a separate commit for documentation and testing.

added basic route for sites

---

wp1-frontend/cypress/fixtures/sites.json
wp1-frontend/cypress/integration/createList_page.spec.js
wp1-frontend/src/components/CreateSimpleList.vue
wp1-frontend/src/components/MyLists.vue

This fixes #367 
Shouldn't this be under the `Create Simple List` page (currently in mock-up it was under My Lists)?

added UI for creating list

---

wp1/logic/selection.py
wp1/logic/selection_test.py

added function and tests for validating article names

---

openapi.yml
wp1-frontend/cypress/integration/createList_page.spec.js
wp1-frontend/src/components/CreateSimpleList.vue
wp1/logic/selection.py
wp1/logic/selection_test.py
wp1/web/app.py
wp1/web/selection.py
wp1/web/selection_test.py
wp1/web/sites.py
wp1/web/sites_test.py

Create backend endpoint for saving simple lists

---

db/migrations/20210706_01_4UFpC-add-created-at-timestamp-to-selections-table.py

This will be displayed to the user and used to sort selections in reverse chronological order.

Add created_at timestamp to selections table

---

wp1-frontend/src/cards.scss
wp1-frontend/src/components/ArticleTableNameFilter.vue
wp1-frontend/src/components/ArticleTablePageSelect.vue
wp1-frontend/src/components/ArticleTableRatingSelect.vue
wp1-frontend/src/components/MyLists.vue

This is just the UI part of saved lists.
Code for backend part, authentication and cypress tests are to be added further.

Display saved lists in MyLists

---

wp1-frontend/cypress/fixtures/save_list_failure.json
wp1-frontend/cypress/integration/createList_page.spec.js
wp1-frontend/src/components/CreateSimpleList.vue

Fixed error in frontend

---

docker-compose.yml

Redirect HTTP to HTTPS for both web hosts

---

supervisord.conf

Add materializer worker queue

---

db/migrations/20210813_01_Ki0ld-fix-builders-timestamp-columns.py
db/migrations/20210813_02_g8XdS-fix-selections-timestamp-columns.py
wp1/logic/builder_test.py
wp1/selection/abstract_builder_test.py
wp10_test.up.sql

Fix wp10 db timestamp columns

---

wp1/storage.py
wp1/storage_test.py
wp1/web/storage.py
wp1/web/storage_test.py

We need the storage to be accessible from places in the app other than the web context.

Refactor s3 storage so that it is more general to the app

---

openapi.yml
wp1-frontend/cypress/fixtures/list_data.json
wp1-frontend/cypress/integration/myLists_page.spec.js
wp1-frontend/src/components/CreateSimpleList.vue
wp1-frontend/src/components/MyLists.vue
wp1/logic/builder.py
wp1/logic/builder_test.py
wp1/web/selection.py
wp1/web/selection_test.py
wp1/web/sites_test.py

This fixes #406 
I will be adding cypress tests in the following commit.

frontend displays lists in MyLists

---

wp1/logs.py
wp1/logs_test.py

Stop adding "... articles by quality" category to log pages

---

wp1/tables_test.py
wp1/templates/table.jinja2
wp1/templates/table_helpers.jinja2

Use space delimited project names when calling the WikiWork template

---

README.md
docker/dev-db/README.md
docker/dev-db/enwp10_dev.dump.sql

Also adds directions to the README for the docker image to migrate and perform this task again in the future.

Apply migrations to dev database and check in new dump

---

.gitattributes
.pre-commit-config.yaml
docker-compose-test.yml
wp1/credentials.py.example
wp1/tables_test.py
wp1/web/app_test.py

Isolate tests from local db and redis

---

db/migrations/20220904_01_sroTV-change-params-field-in-builders-to-longblob.py
wp1-frontend/src/components/SimpleList.vue
wp1/selection/models/simple_builder.py
wp1/selection/models/simple_builder_test.py

Fixes #503 
This PR changes the builder `b_params` column from BLOB to LONGBLOB, deletes any corrupted builders whose data have already been truncated, and institutes an arbitrary 10 MB limit on list length.

Change list column from BLOB to LONGBLOB

---

wp1-frontend/cypress/integration/myLists_page.spec.js
wp1-frontend/src/components/MyLists.vue
wp1/logic/builder.py

Fixes #434
Simple implementation of a progress spinner that simply checks if a list has a URL for downloading. If not, it displays the spinner and polls for the entire list of selections. Once every selection has a URL, polling stops.

Implement progress spinner in "My Lists" table

---

wp1/selection/abstract_builder.py
wp1/selection/models/sparql.py
wp1/selection/models/sparql_test.py
wp1/web/builders.py

Use the project name when building SPARQL queries

---

wp1-frontend/cypress/e2e/createSimpleList.cy.js
wp1-frontend/cypress/e2e/createSparqlList.cy.js
wp1-frontend/cypress/e2e/updateSimpleList.cy.js
wp1-frontend/cypress/e2e/updateSparqlList.cy.js
wp1-frontend/src/components/BaseBuilder.vue

Show spinner and disable Selection save/update buttons on click, with tests

---

.github/workflows/workflow.yml
wp1-frontend/.env.staging
wp1-frontend/cypress.config.js

Update Cypress tests to run against production javascript binary

---

wp1-frontend/src/components/SecondaryNav.vue

Launch SPARQL selections by adding them to secondary nav

---

wp1-frontend/src/components/MyLists.vue

Use raw timestamps as sorting values in table

---

wp1/logic/builder.py
wp1/logic/builder_test.py

Don't try to delete object keys for selections without one

---

docs/developer/index.md
docs/index.md
docs/user/index.md
mkdocs.yml

First of potentially many docs PRs. Shouldn't affect website operation at all.

Add barebones docs structure

---

wp1/custom_tables/us_roads.py
wp1/selection/models/sparql.py
wp1/selection/models/sparql_test.py

Unescape URLs returned from WDQS

---

wp1-frontend/src/App.vue

Update header to add docs link

---

wp1-frontend/src/components/MyLists.vue
wp1/selection/abstract_builder.py

Fixes #603 
Depending on which is pending, the poll rate is set accordingly. Every 20 seconds for selections and every 5 minutes for ZIM files.

Poll for ZIM status on My Lists page

---

openapi.yml

Update OpenAPI docs

---

wp1/logic/builder.py

The query for `latest_zim_file_for` was being used to get the ZIM status for the current Builder. However, that will always return a ZIM that is in the FILE_READY state, instead of the ZIM for the latest Selection of the Builder, which is what we want when creating new ZIMs. Additionally, the query had an error where it wasn't restricting the returned ZIMs to those that matched the `builder_id` of the given builder. So all ZIMs of a given version were being returned.

Fix bugs with ZIM status

---

wp1-frontend/cypress/e2e/myLists.cy.js
wp1-frontend/src/components/MyLists.vue

Additional frontend fix for deleted ZIMs

---

requirements.txt
wp1-frontend/src/components/PetscanBuilder.vue
wp1-frontend/src/components/SecondaryNav.vue
wp1-frontend/src/main.js
wp1/selection/models/petscan.py
wp1/selection/models/petscan_test.py
wp1/web/builders.py

Re-adding commits reverted in #643 (improperly merged to HEAD).

Re-commit reverted PR (Petscan Builder)

---

wp1/logs.py
wp1/logs_test.py

Use <noinclude> for {{Log}} message in logs

---

wp1-frontend/src/components/PetscanBuilder.vue

Add Petscan links

---

.codecov.yml

Try ignoring paths in codecov

---

.github/workflows/ci.yml
docker/dev-workers/Dockerfile
docker/workers/Dockerfile
requirements.txt

Upgrade to Python 3.12

---

.github/workflows/ci.yml
docker-compose-test.yml
wp1/logic/builder_test.py

Change CI db to MariaDB

---

wp1-frontend/package.json
wp1-frontend/yarn.lock

Upgrade Cypress to version 13

---

wp1-frontend/src/components/BaseBuilder.vue
wp1/logic/builder.py
wp1/web/builders.py

Add additional logging

---

wp1/selection/models/petscan.py
wp1/selection/models/petscan_test.py

Fixes #792 
WMF Cloud VPS URLs have changed from wmflabs -> wmcloud.

Update petscan URL

---

README.md
docker-compose-dev.yml
wp1/credentials.py.dev.e2e
wp1/credentials.py.dev.example
wp1/credentials.py.example
wp1/storage.py
wp1/storage_test.py

Make selection materialization S3 server URL configurable

---

docs/requirements.txt
docs/user/index.md

Update link in docs and update PyYAML version

---

db/migrations/20250330_01_zaRQa-migrate-last-7-days-of-logs.py

Add migration for past 7 days of logs as a one time move to Redis

---

db/migrations/20250325_01_sFddz-add-article-count-to-selection-table.py
wp1/logic/selection.py
wp1/logic/selection_test.py
wp1/models/wp10/selection.py
wp1/selection/abstract_builder.py
wp1/selection/abstract_builder_test.py
wp1/zimfarm.py
wp10_test.up.sql

Includes migration code to retrieve all selections from S3 and populate article counts.
First backend part of addressing #816.

Calculate and store article counts when materializing selections.

---

.github/workflows/ci.yml
.github/workflows/publish.yml

https://github.com/actions/runner-images/issues/11101

Update github CI runner Ubuntu versions

---

wp1/credentials.py.dev.example
wp1/credentials.py.example
wp1/zimfarm.py
wp1/zimfarm_test.py

Use optimisationCacheUrl flag when requesting ZIM file

---

wp1/logic/selection.py
wp1/logic/selection_test.py
wp1/zimfarm.py
wp1/zimfarm_test.py

Use "magic" formula for calculating zimfarm memory

---

wp1-frontend/src/components/ZimFile.vue
wp1/web/builders.py

Send credentials in article_count request. Improve error handling

---

wp1-frontend/src/components/ProjectTable.vue
wp1/tables.py
wp1/web/projects.py
wp1/web/projects_test.py

We already had this data, it was just a matter of adding it to the table data and displaying it.

Add last update timestamp to project tables

---

wp1/logic/api/page.py
wp1/logic/project.py
wp1/tables.py

For helping with debugging #875. This can be reverted once the issue is solved.

Change logging level and add more debug logging

---

wp1/api.py
wp1/logic/api/page.py

Login to API site before attempting to use it

---

enqueue-global.py
wp1/logic/project.py
wp1/tables.py

Add more logging to project updating and table creation processes.

More logging

---

wp1/credentials.py.dev.example
wp1/credentials.py.e2e
wp1/credentials.py.example
wp1/zimfarm.py
wp1/zimfarm_test.py

Allow mwoffliner image to be configurable, and use ActionParse renderer

---

wp1/logic/builder.py
wp1/logic/builder_test.py
wp1/logic/zim_schedules.py
wp1/logic/zim_schedules_test.py
wp1/queues.py
wp1/queues_test.py

Add/Update `zim_file_id` to `zim_schedule` when the scheduled file is requested from the zimfarm.

add support for updating `zim_schedule` with `zim_file_id`

---

wp1/zimfarm.py
wp1/zimfarm_test.py

Remove ZIMFARM schedule deletion in request_zimfarm_task function

---

wp1/logic/builder.py
wp1/logic/builder_test.py
wp1/web/builders_test.py
wp1/zimfarm.py
wp1/zimfarm_test.py

Refactor zimfarm task to decouple schedule and task

---

wp1-frontend/cypress/e2e/zimFile.cy.js
wp1-frontend/src/components/ZimFile.vue

Fix validation for ZIM files

---

wp1-frontend/src/components/ZimFile.vue
wp1/logic/zim_schedules.py
wp1/logic/zim_schedules_test.py
wp1/web/builders.py
wp1/web/builders_test.py
wp1/web/emails.py

Add frontend option for scheduling zim generations

---

wp1-frontend/src/components/ZimFile.vue
wp1/logic/builder.py
wp1/logic/zim_schedules.py
wp1/logic/zim_schedules_active_test.py
wp1/web/builders.py
wp1/web/builders_schedule_test.py
wp1/web/builders_test.py

Manually delete zim schedule

---

wp1-frontend/src/App.vue

Add footer for Privacy policy

---

db/migrations/20250821_01_add_email_confirmation_token_to_zim_schedules.py
wp1-frontend/src/App.vue
wp1-frontend/src/components/ZimFile.vue
wp1/constants.py
wp1/logic/builder.py
wp1/logic/builder_test.py
wp1/logic/zim_schedules.py
wp1/logic/zim_schedules_active_test.py
wp1/logic/zim_schedules_email_test.py
wp1/logic/zim_schedules_test.py
wp1/models/wp10/zim_schedule.py
wp1/models/wp10/zim_schedule_test.py
wp1/queues.py
wp1/queues_test.py
wp1/templates/generated-scheduled-zim-email.html.jinja2
wp1/templates/zim-email-confirmation.html.jinja2
wp1/templates/zim-email-error.html.jinja2
wp1/web/app.py
wp1/web/builders.py
wp1/web/builders_schedule_test.py
wp1/web/builders_test.py
wp1/web/emails.py
wp1/web/emails_confirmation.py
wp1/web/emails_confirmation_test.py
wp1/web/emails_test.py
wp1/web/zim_emails.py
wp1/web/zim_emails_test.py
wp1/zimfarm.py
wp1/zimfarm_test.py
wp10_test.up.sql

Delete scheduled zim on builder delete

---

wp1/logic/zim_schedules.py

fix: update email confirmation URLs to use the correct path format

---

wp1/logic/zim_schedules.py
wp1/logic/zim_schedules_test.py

fix: update query in `get_username_by_zim_schedule_id` to include builders table
