openzim/wp1

lucky/enqueue-all.py, lucky/supervisord.conf, lucky/worker.py
This branch changes the way workers are set up so that they use a custom script (not a custom class) for doing the work. This custom script largely delegates to the rq `Worker` class. It is mainly provided so that the import of the api module and the connection to Wikipedia (logging in) can be done prefork, to avoid "too many login attempts in a row" errors with the API.
We also provide changes to enqueue-all to allow for only upload jobs to be queued.
=> Worker job changes

lucky/requirements.txt, lucky/supervisord.conf, lucky/worker.py
Adds a dependency on `rq-retry` and `rq-scheduler` in order to retry failed jobs, first after 30 seconds, then after 3 minutes, up to 4 total retries (5 total attempts).
=> Retry jobs

lucky/lucky/logic/project.py, lucky/lucky/tables.py, lucky/lucky/wiki_db.py, lucky/lucky/wp10_db.py, lucky/worker.py
By creating a global variable in each database module (WIki replica db and WP1.0 db), we can connect to the databases "prefork" in the worker script, so all worker jobs will share a connection (instead of connecting to the database in each worker sub process).
As part of this, we add calls to wp10db.ping() which will check for a stale connection and reconnect.
This is a partial fix to #23.
=> Configure db connections globally

docker-compose.yml, docker/web/Dockerfile, docker/web/start.sh, lucky/requirements.txt, web.Dockerfile
Create a 'web' Docker image that is similar to the workers image, except instead of starting workers, it installs the code and its requirements and then starts the `rq-dashboard` process.
The process is started with basic auth enabled, with the data being read from a file named `app/rq-credentials.txt` which should be mapped from the host container.
This will later be replaced with a full Flask app where rq-dashboard is only one part of it.
=> Start of web Docker image

docker/workers/Dockerfile
* `flock -w 0` is better represented by `-n` (don't wait for lock)
* The flock command must be preceded by the `-c` flag and quoted
* A crontab entry has 6 space separated parts not 5
* There is no need for 'root' in the cron entry, it doesn't do anything
=> Fix flock/cron command

wp1/api.py, wp1/api_test.py, wp1/tables.py, wp1/tables_test.py
=> Refactor api module and retry login if Unathenticated error is thrown

wp1/templates/table.jinja2
Fixes #50. We prepared an `is_single_col` parameter for the template, but forgot to use it.
=> Fixes the women's cricket table and any other table with a single column

cron/update-global-articles.sh, docker/workers/Dockerfile, enqueue-all.py, update-global-articles.py, wp1/logic/project.py, wp1/logic/project_test.py
Since we discovered in #71 that updating the global_articles table cannot be done in parallel, add a cron job for updating it at 4 AM UTC.
This PR includes a refactor of the code for getting the names of all projects to update, and tests for the same. It also includes some refactoring of tests so that they are better organized.
(Fixes #71)
=> Create a separate cron job for updating the global_articles table

wp1/api.py, wp1/api_test.py
=> Try a no-op to refresh login status on the API site object

wp1/api.py, wp1/api_test.py
As stated in the comment in the code, since the site is tied to the page itself, get a new page object from the API when we re-login. Fixes #69.
=> New strategy for dealing with failed page edits

cron/enqueue-all.sh
Additional fix for #69, otherwise the workers will probably hit a login rate limit. See discussion in #80.
=> Restart the upload worker jobs as part of the cron job to avoid #69

wp1/logic/project.py, wp1/logic/project_test.py, wp1/logic/rating.py
Fixes #83 
This bug was introduced when we switched from doing unseen articles after each quality/importance run, to doing them all at the end. Because of that, the `old_rating` doesn't get updated in between runs. So, when a new article appears that has both a quality and an importance rating, the rating for quality would be written, then it would be re-written with importance as a "new" rating, which would set the quality to NULL.
This manifests as duplicate logs because the next day, the `old_rating` is there, but has quality NotA-Class, so we write a log that the quality went from NotA-Class -> Whatever, which shows up in the logs as "assessed".
=> Fix for duplicate logs.

wp1/logic/api/page.py, wp1/logic/api/page_test.py
Fixes #96.
The API library that the old bot was using would return `Category:Foo` as just `Foo` and we were later adding the namespace back in. This PR updates the API wrapper so that it behaves the same way.
=> Remove extraneous namespace returned by API

wp1/logic/project.py
The main update_project function was passing extra_assessments['extra'], while the update_category function was also looking for an 'extra' key in the top level extra_assessments variable. This means the key was never found and extra assessments were being ignored.
Should fix #94.
=> Fix bug where inner dictionary was getting passed in

wp1/logs.py, wp1/logs_test.py
The main change is:
```
'log_date': dt.strftime('%b %d, %Y'),
```
to
```
'log_date': dt.strftime('%B %-d, %Y'),
```
The entire rest of the change is just yapf going crazy.
=> Change date format for logs

README.md, wp1/logic/project.py, wp1/logic/project_test.py
This PR refactors the way article assessments are inserted/updated into the database. Instead of inserting them as they are found, a list of ratings for an article is made and then later that list of ratings is sorted based on the "score" value for that rating. This means that if an article is rated both Start-Class and A-Class, only the A-Class is taken and recorded.
By deferring the decision to update a rating until all "candidate" ratings have been collected, we also avoid rating thrashing, where logs for ratings are recorded with the article going back and forth between ratings, as seen in #89.
=> Avoid recording duplicate assessments

wp1/logs.py, wp1/logs_test.py
This PR implements a strategy of truncating the 7 days of logs until they fit. It first drops the oldest entry, then the next oldest, etc.
If even the newest entry is too big to fit on its own, then a simple message is displayed.
This might not be as necessary once #103 goes live, since the duplicated assessments were probably a large source of the extra long logs. But it can't hurt.
Fixes #95.
=> Back off updating log dates when they are too big

wp1/logs_test.py, wp1/templates/log_helpers.jinja2
As mentioned in https://github.com/openzim/wp1/issues/93#issuecomment-529734961, it may still be possible (somehow) for log entries to have literal NULL/None values for l_old. In this PR we guard against that.
Fixes #93.
=> Guard against None values for l_old

wp1/api_test.py, wp1/logic/project.py, wp1/tables.py
I accidentally left in a debug print statement that was printing all the ratings for all the projects. This was causing the logs to grow extremely fast, as well as be filled with junk. Also removed some other junky print statements that weren't as serious at the same time.
=> Remove extraneous print statements

docker-compose.yml
This is an attempt to reduce Docker logs size on master system.
@audiodude At home I have a strange error with `docker-compose`... but this seems unrelated to that PR.
```
$ docker-compose images
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default value Additional properties are not allowed ('name' was unexpected)
$ docker-compose --version
docker-compose version 1.17.1, build unknown
```
=> Limit Docker logs size

.travis.yml, docker/web/start.sh, requirements.txt, wp1/api_test.py, wp1/logic/project.py, wp1/web/app.py, wp1/web/app_test.py, wp1/web/base_web_testcase.py, wp1/web/db.py, wp1/web/templates/index.html.jinja2
Replaces the rq dashboard at "/" with a hello page that simply lists the number of projects that we are serving. However, this serves as a good test for database connectivity, Flask being installed correctly, etc.
The rq dashboard is now on "/rq", with the same credentials as before, which are now taken from the environment.
=> FIrst "hello world" version of web app

wp1/logic/category.py, wp1/logic/project.py, wp1/logic/project_test.py
To partially address #116, I've added more sanity checks for the custom categories coming back from Wikipedia (since anyone could put anything there) and fixed some issues with the database query to update categories, namely that it wasn't committing the query and it wasn't updating anything in the case the category already existed.
=> Fix category update and more checks on custom categories

wp1/logic/project.py, wp1/logic/project_test.py
In #103, we added code for looking at "all" the ratings of an article (even though it should technically only be in one category and have one rating) and taking the highest ranking rating for that article (so "A-Class" would override "Stub-Class" if both were present).
However, the mechanism by which that operated didn't take into account custom categories, it only used the categories that are "built-in" so to speak. So when #105 was submitted, we started recognizing custom categories again, only to bomb out at the sorting part.
This PR, with test, should fix that, and fix #116.
=> Use discovered ranking (incl. for custom categories) when sorting ratings.

wp1/wiki_db.py, wp1/wiki_db_test.py, wp1/wp10_db.py, wp1/wp10_db_test.py
We have been seeing lots of db connection issues, primarily because we don't have enough db connections for all of our workers. Retrying like this should introduce some latency, but also some resilience.
=> Retry db connections up to four times every 5 seconds

.gitignore, wp1/base_db_test.py, wp1/credentials.py, wp1/db.py, wp1/db_test.py, wp1/environment.py, wp1/wiki_db.py, wp1/wiki_db_test.py, wp1/wp10_db.py, wp1/wp10_db_test.py
In order to facilitate #137 it would be advantageous to ship "default" development credentials in credentials.py. In the past, this file has been excluded from source control, and while we could simply ask developers to configure it manually when they set up the project, it seems much more attractive to ship with reasonable defaults so that users can get up and running more quickly.
This PR adds a credentials.py file, and introduces an environment.py file which is simply an enum. The redundant database connection methods, which were duplicated, are consolidated in db.py.
=> Create Development/Production "environments"

wp1/logic/project.py, wp1/logic/project_test.py, wp1/time.py
Create new projects when they are found, and properly update count, qcount, and icount.
The latter variables were not being set properly on the project, even though they were being computed, and a bug in the test prevent us from catching this.
=> Fix some project processing

.gitignore, README.md, docker-compose-dev.yml, wp1/credentials.py.example, wp1/db.py
This PR is the logical replacement to #143. However instead of creating the docker image for the development database in this repo itself, it is now served by the repo at:
https://github.com/openzim/wp1-dev-database
This PR provides a docker-compose-dev.yml file that can be used to pull the development db and start it running.
The `credentials.py` have once again been moved to `credentials.py.example` and a gitignore rule has been added for `credentials.py`. This is because developers are now encouraged to use their toolforge DB credentials in development to SSH tunnel to the enwiki_p replica database.
The README has also been updated.
=> Setup the environment for a development database

wp1/db.py
The changes in #146 fixed the db module for when credentials.py doesn't exist, mostly for unit tests. This change fixes it to work again when credentials.py *does* exist.
=> Fix db for when there is NOT an ImportError

enqueue-all.py, enqueue-global.py, enqueue-project.py, wp1/credentials.py.example
And use the environment specific credentials in enqueue-* scripts.
This allows a development user to update his or her development database using those scripts.
=> Put Redis credentials in credentials.py.example

conf.json, wp1/logic/project.py, wp1/logic/project_test.py
This is needed for new projects, since there is no actual wiki category for "NotAClass" category, but it's used in the assessment table. Without this, new projects won't have an "other" category displayed in their assessment table.
A consequence of this is that we need to re-run the update job for all of the dev database projects, so that the dev server produces accurate tables.
=> Create the NotA-Class categories when updating a project

openapi.yml, wp1-frontend/src/App.vue, wp1-frontend/src/components/Autocomplete.vue, wp1-frontend/src/components/ProjectTable.vue, wp1-frontend/src/components/WikiLink.vue, wp1-frontend/yarn.lock, wp1/api.py, wp1/tables.py, wp1/tables_test.py, wp1/web/projects.py, wp1/web/projects_test.py
This PR creates a mapping from the project data used to generate the wikicode tables for Wikipedia, to a Vue component which displays a similar table on the homepage of the frontend server.
It adds a new endpoint to the API, which is documented in `openapi.yml`.
There are also some changes to the Autocomplete component to allow it to pass the project that is selected. Future changes will introduce routing so that users can visit the table page of a project directly.
=> Display project table on Frontend homepage when project is selected

wp1/web/app.py, wp1/web/db.py
Originally the API server was setup to connect to both the WP 1.0 application db (wp10db) and the Wikipedia replica db (enwiki_p, or wikidb in the code).
I no longer believe that the wiki db connection is necessary so I'm removing the reference to it.
=> Remove reference to wikidb from api server

openapi.yml, wp1-frontend/src/components/ArticlePage.vue, wp1-frontend/src/components/ArticleTable.vue, wp1-frontend/src/components/Autocomplete.vue, wp1-frontend/src/components/ProjectPage.vue, wp1-frontend/src/components/ProjectTable.vue, wp1-frontend/src/labels.scss, wp1-frontend/src/main.js, wp1/constants.py, wp1/logic/rating.py, wp1/logic/rating_test.py, wp1/models/wp10/rating.py, wp1/tables.py, wp1/web/projects.py, wp1/web/projects_test.py
This feature seeks to emulate the article lists from the original website, such as [here](https://tools.wmflabs.org/enwp10/cgi-bin/list2.fcgi?run=yes&projecta=Modern_philosophy&importance=Top-Class&quality=B-Class).
Currently, it only returns up to 100 results for a particular Quality/Importance specification, with no pagination. The intention is to improve upon that, but this seems like a good start.
Like the project tables, article tables get their own page in the site that is bookmarkable and history navigation works.
I will be adding a commit in a little bit to update the Swagger spec for the new endpoint.
=> List articles and show links to article lists in project tables

openapi.yml, wp1-frontend/src/components/ArticlePage.vue, wp1-frontend/src/components/ArticleTable.vue, wp1-frontend/src/components/ProjectTable.vue, wp1-frontend/vue.config.js, wp1/constants.py, wp1/logic/project_test.py, wp1/logic/rating.py, wp1/logic/rating_test.py, wp1/web/projects.py, wp1/web/projects_test.py
This PR adds pagination to the article tables. Previously, only the first 100 results were shown and there was no way to see the rest.
Now, if there are more than 100 results, a page indicator is shown at the top of the table, with links to additional pages of results.
These pages are bookmarkable and navigable, like other pages in the site.
=> Article page pagination

wp1/tables.py, wp1/tables_test.py
Fixes #160 
Even if you freshly generated the tables on every request, the data wouldn't change because the underlying update jobs only run once per day. By caching the result of the table after the upload job runs, we make sure that the frontend can return a result for all projects, even the huge ones, and generally reduce the load on the db.
=> Cache generated table data as a pickle, and tests for the same

wp1/logic/rating.py, wp1/logic/rating_test.py
Although "Assessed" isn't a real quality class stored in the database, the old server allows for queries for this class when browsing project tables. For feature parity, this PR adds support for it in the backend, which makes the frontend no longer return no results for queries of this kind.
=> Add special handling for links from table with quality=Assessed-Class

enqueue-all.py, enqueue-project.py, openapi.yml, wp1-frontend/src/components/UpdatePage.vue, wp1-frontend/src/main.js, wp1/logic/api/page.py, wp1/logic/project.py, wp1/logic/project_test.py, wp1/logic/rating.py, wp1/queues.py, wp1/queues_test.py, wp1/redis_db.py, wp1/web/projects.py, wp1/web/projects_test.py
Manual updates have two stages of progress: waiting in the RQ worker queue behind other manual updates (though this will likely be rare), and actually updating the articles that need to be updated.
This PR creates a progress bar and a status string that informs the user of the current state of their project. This information remains for 10 minutes after the job has completed.
=> Show progress of manual updates

wp1-frontend/src/App.vue, wp1-frontend/src/components/ArticlePage.vue, wp1-frontend/src/components/IndexPage.vue, wp1-frontend/src/components/ProjectPage.vue, wp1-frontend/src/components/UpdatePage.vue
Fixes #180.
Also resizes components to only be half page width when the viewport is "xl".
=> Add welcome banner for new WP 1.0 frontend

wp1/constants.py, wp1/tables.py, wp1/templates/format.jinja2
This is optionally controlled by a constant, link_to_v2, which means that the old linking behavior is preserved and can be turned back on at any time.
=> Link to v2 of the Web frontend in project tables

openapi.yml, wp1-frontend/src/App.vue, wp1-frontend/src/components/ArticlePage.vue, wp1-frontend/src/components/ArticleTable.vue, wp1-frontend/src/components/Autocomplete.vue, wp1-frontend/src/components/IndexPage.vue, wp1-frontend/src/components/ProjectPage.vue, wp1-frontend/src/components/UpdatePage.vue, wp1-frontend/src/main.js, wp1/web/projects.py, wp1/web/projects_test.py
Fixes some alignment issues with paragraphs on a few pages. Also removes the Autocomplete box from the Article listing page to make it less busy.
If the main page is loaded with a non-existant project: (eg [http://wp1.openzim.org/#/project/Paris](http://wp1.openzim.org/#/project/Paris)), the page is simply loaded in it's default, empty state.
The same is true of the manual update page (eg [http://wp1.openzim.org/#/update/Paris](http://wp1.openzim.org/#/update/Paris)), the page simply loads as if no Project was chosen.
These two default states make sense, since the only way the page can be reached with an invalid project is through URL hacking anyways.
The article listing page also refuses to list the results for non-existant projects, and this time displays a "not found" message, in order …
=> Guard against pages loading with non-existant projects and other frontend cleanups

wp1/logic/rating.py
We can't join against importance if it always equals NotAClass. This fixes the query.
=> Fixes #194

wp1-frontend/src/App.vue, wp1-frontend/src/components/ProjectTable.vue
Removed the background color of the main table, fixed the foreground for the cells with background colors, and fixed the link color overall.
Fixes #199
=> Update colors for better accessiblity contrast

openapi.yml, wp1-frontend/src/components/ArticleTable.vue, wp1/api.py, wp1/api_test.py, wp1/models/wp10/rating.py, wp1/models/wp10/rating_test.py, wp1/web/app.py, wp1/web/articles.py, wp1/web/articles_test.py
This now looks like this:
The ( t ) and ( h ) in parenthesis are links to the current talk and history pages of the article. The timestamps for quality and importance now link to the revisions on Wikipedia that were active at that time. And the ( t ) next to the timestamps links to the talk page at that revision.
Fixes #175
=> Add talk, history and old revision/old revision talk links to the article listing page

wp1-frontend/src/components/ArticleTable.vue, wp1/models/wp10/rating.py, wp1/web/projects_test.py
Instead of just randomly chopping off '-Class' for the category names in the article table, use the database mappings, which are already available at the /categoryLinks endpoint.
Fixes #209.
=> Display proper category names in article table

wp1-frontend/src/components/ArticlePage.vue
If the user has gotten to an articles list with _ instead of space, replace the spaces on back.
Fixes #218
=> Fix article pages "back" links

.gitignore, wp1/api.py, wp1/api_test.py
Change login so that it:
1. Does not happen automatically on startup/import and
2. Persists the cookies between worker processes so that login can happen drastically less often
Fixes #226
=> Drastically reduce the number of logins

wp1/tables.py
Ignore the cache when doing a table upload. This ensures that both manual and scheduled uploads use the latest data.
=> Fix caching bug

wp1-frontend/src/App.vue, wp1-frontend/src/components/ArticlePage.vue, wp1-frontend/src/components/ArticleTable.vue, wp1-frontend/src/components/ArticleTableRatingSelect.vue, wp1-frontend/src/components/Autocomplete.vue, wp1-frontend/src/components/ComparePage.vue, wp1-frontend/src/components/IndexPage.vue, wp1-frontend/src/components/ProjectPage.vue, wp1-frontend/src/components/UpdatePage.vue, wp1-frontend/src/main.js, wp1/logic/rating.py, wp1/logic/rating_test.py, wp1/models/wp10/rating.py, wp1/web/projects.py, wp1/web/projects_test.py
Fixes #237.
An implementation of a separate page for comparing articles across projects, at the /compare URL. Each project is selected from a separate autocomplete drop down. An ArticleTable is displayed once the project and quality/importance selections has been made. Pagination, custom pagination, and article name filtering all work for the returned ArticleTable.
Additionally, changes to the settings of the page are reflected in the URL, so pages with certain listings can be bookmarked and navigated through.
=> Implement page for comparing articles across projects

wp1-frontend/src/App.vue
Remove line about old tool being available. It has been shut down and now redirects only to the new tool.
=> Update new tool welcome message

docker/workers/Dockerfile
The `update-global-articles.sh` script somehow became non-executable in the Docker container, which meant it couldn't be run daily, which was causing #249 (since the article counts weren't being updated, the global table was identical).
Also, write the log files for the cron jobs to the proper wp1bot directory so they can be read from the host.
Fixes #249 
Fixes #250
=> Make the cron jobs all executable and update log location

wp1-frontend/src/components/Autocomplete.vue
@audiodude The autocomplete search box now overlaps the page content rather than pushing it down.
This resolves #281
=> added absolute position to autocomplete search box

wp1-frontend/src/components/Autocomplete.vue, wp1-frontend/src/components/UpdatePage.vue
new manual update not starting until previous update in progress.
This resolves #186
=> Manual update changes

.github/workflows/python.yml, wp1/logic/page.py
This is a PR to replace travis CI with GitHub Actions. I am proceeding in stages, first trying to get a basic Python build and test workflow working, then moving on to adding Codecov and Codefactor, and finally getting the Cypress test environment configured.
=> Replace Travis CI with GitHub Actions: Step 1 basic Python

.github/workflows/workflow.yml
We were already using a Redis service in the `python-nose` job, but it's also required in the `frontend-cypress` job.
=> Add Redis to Cypress CI job

README.md, wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/web/app.py, wp1/web/dev/projects.py
This PR introduces a `dev_projects` blueprint. If the code is running where ENV == Environment.DEVELOPMENT (as is the case in the example credentials, and is NOT the case in production), the Flask application setup will include dev_projects first, and then the regular projects blueprint.
The effect of this is that endpoints defined in `dev_projects` are used instead of/before the regular ones. This allows us to mock out the manual update process in development, which is what it is immediately used for.
As provided in this PR, the manual update is API compatible with the normal path as far as the frontend is concerned. However it has the following features:
- The "lockout" time between updates is 5 minutes instead of 1 hour.
- All updates take 60 seconds, with the progress being 1/60, 2/60 …
=> Development versions of manual update API server code

requirements.txt
Supervisor has a bug in Python 3.8, detailed here: https://discord.com/channels/790803387050360873/802739712070647840/839719688161329173
Upgrade to 4.2.2 to avert it.
Fixes #329
=> Upgrade supervisor for Python 3.9

requirements.txt, wp1-frontend/cypress/integration/article_page.spec.js, wp1-frontend/src/App.vue, wp1-frontend/src/components/ArticleTableNameFilter.vue, wp1-frontend/src/components/ArticleTablePageSelect.vue, wp1-frontend/src/components/ArticleTableRatingSelect.vue, wp1/base_db_test.py, wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/web/app.py, wp1/web/oauth.py, wp1/web/oauth_test.py
This PR adds a new `oauth` blueprint to the backend API server that initiates and completes the OAuth login flow with the Meta Wikipedia server. The end result is that our app receives a username and user id for the user, and they are "logged in" to our app, via a session cookie which stores the same.
=> User login with OAuth via mwoauth library

wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/web/app.py, wp1/web/oauth.py, wp1/web/oauth_test.py
The client side call to `/identify` uses `credentials: include` in the fetch request. However, this is only supported by a cross domain server (such as wp1.openzim.org -> api.wp1.openzim.org) if the `supports_credentials=True` is configured for Flask-CORS. This parameter requires that the list of origins be explicitly listed, so we add an additional configuration to credentials.py
=> Configure CORS for supports_credentials=True

db/migrations/20210705_01_TgcHL-add-selections-table.py, wp1/models/wp10/selection.py, wp1/models/wp10/selection_test.py
This PR adds a database migration for adding the selections table to the WP10 MariaDB database. Developers will have to migrate their development databases, and the production database migrations will also have to be run.
There is also a model added for Selection.
Fixes #374
=> Database migration and model for Selections

db/migrations/20210706_01_4UFpC-add-created-at-timestamp-to-selections-table.py, wp1/models/wp10/selection.py
Also add a logger to the Selection model, because it requires it.
=> Fix column name in created_at migration

db/migrations/20210724_01_p2yUM-remove-deprecated-selections-table.py, db/migrations/20210724_02_PR3Js-list-builders-table.py, db/migrations/20210724_03_C7FOH-selections-table.py, wp1/models/wp10/builder.py, wp1/models/wp10/builder_test.py, wp1/models/wp10/selection.py, wp1/models/wp10/selection_test.py
This PR includes a migration that removes the old selections table, since it conflates the ideas of list builders and selections as discussed in #370. The PR further creates both a table for list builders (named just "builders") which the user can input and save, and selections, which are materialized lists of articles that are generated from builders but stored in the s3-like backend.
There is a one-to-many relationship between builders and selections, in that many selections (presumably of different content types) can be generated from a builder.
This PR also provides basic `attrs` based classes for modeling the data in these tables.
=> New schema for Selections that respects the difference between Selections and List Builders

db/migrations/20210728_01_eJYGE-add-model-to-builders.py, wp1/constants.py, wp1/logic/selection.py, wp1/models/wp10/builder.py, wp1/models/wp10/builder_test.py, wp1/models/wp10/selection.py, wp1/selection/abstract_builder.py, wp1/selection/abstract_builder_test.py, wp10_test.down.sql, wp10_test.up.sql
Includes database migration to add b_model to builders table and necessary test schema files.
This code doesn't do much on it's own, but provides an interface for a subclass to implement the not-implemented build method. Given such an implementation, and when passed a valid builder and a content type, the AbstractBuilder materialize method will build the selection from the builder and store the resultant selection list in s3. It will also save a Selection record in the WP 1.0 database for the selection list.
Fixes #394
=> AbstractBuilder with tests

requirements.txt, wp1/credentials.py.example, wp1/web/base_web_testcase.py, wp1/web/storage.py, wp1/web/storage_test.py
This PR creates sample entries in credentials.py.example for Development and Production for the s3 storage backend. It also provides a way to get the storage from the web frontend, as well as a way to mock that storage backend in web tests.
=> Setup backend storage (s3-like) for web app

wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logs_test.py, wp1/queues.py, wp1/queues_test.py
This PR provides methods in `queues.py` for materializing a builder given the ID of the builder in the db, the class to use for materialization, and the content_type that is desired.
Fixes #405
=> Methods for enqueuing the materialization of a builder

.github/workflows/workflow.yml, .gitignore, docker-compose-dev.yml, docker/dev-workers/Dockerfile, docker/dev-workers/README.md, supervisord-dev.conf, supervisord.conf
This allows the dev server to actually materialize builders using the dev workers and store the materialized selections in the dev s3.
=> Use new dev-workers image in dev docker compose graph

.github/workflows/workflow.yml, .gitignore, README.md, docker-compose-dev.yml, docker/README.md, docker/dev-workers/.dockerignore, docker/dev-workers/Dockerfile, docker/dev-workers/README.md, wp1/credentials.py.dev.e2e, wp1/credentials.py.dev.example
This PR changes the setup for the dev-workers Docker image, so that in the compose file there is an overlay for both the code it is running (in order to iterate quickly on that code) as well as a new credentials.py file. The new credentials include the local hostnames for the MariaDB and Redis databases inside of the docker-compose graph, as well as potentially contain the developer's credentials for kiwix wasabi S3 storage.
README files have been updated where appropriate for this change.
=> Setup for wp1bot-workers-dev Docker image and compose file

wp1/constants.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/queues.py, wp1/queues_test.py, wp1/selection/abstract_builder.py, wp1/web/selection.py
This PR adds an extra step to the builder saving process, specifically for Simple lists, so that they are added to the materializer queue when they get saved. This means, if the queue is not busy, they will get materialized immediately and stored in the s3-like storage (by the background materializer job).
This is the final step in hooking up Simple list builders!
=> Add builders to the materializer queue when they get saved

wp1-frontend/cypress/fixtures/list_data.json, wp1-frontend/cypress/integration/createList_page.spec.js, wp1-frontend/cypress/integration/myLists_page.spec.js, wp1-frontend/src/App.vue, wp1-frontend/src/components/CreateSimpleList.vue, wp1-frontend/src/components/MyLists.vue, wp1-frontend/src/components/SecondaryNav.vue, wp1-frontend/src/main.js, wp1/constants.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/web/selection.py, wp1/web/selection_test.py
This PR is a bit of cleanup work. It does the following:
- Fixes #415 
- Adds the "Selections" tab to the header nav, which reveals the secondary nav
- Cleans up some frontend styles
- Disambiguates "content-type" from "extension" for list builders
- Cleans up some tests
=> Cleanup some builder logic and frontend styles, add Selection to main navigation

.dockerignore, README.md, build_production_images.sh
Since Docker Hub no longer automatically builds images on repo update (on their free plan), we must have a process in place for building and pushing the production images manually.
While we're add it, add a .dockerignore file to speed up the process dramatically (less data transferred for transient directories).
This is actually perhaps a bit more satisfying than waiting for Docker Hub anyways.
=> New process for building production images manually

wp1/constants.py, wp1/logic/selection.py, wp1/logic/selection_test.py, wp1/selection/abstract_builder.py, wp1/selection/abstract_builder_test.py
We were including the user_id in the object_key for selections, however since this is going to be a public URL, it should not include that information. At the same time, we need to be able to calculate the object_key independently of the initial saving of the selection. Also add some additional tests.
=> Refactor code for calculating object_key for selections

.github/workflows/publish.yml, README.md, build_production_images.sh, docker-compose.yml
This PR finishes the work that was partially completed by directly committing to the master/release branches.
It "adds" the .github/workflows/publish.yml file (though it was technically added earlier) and configures it to publish the images available at: https://github.com/openzim/wp1/packages
It also updates the docker-compose.yml file to pull from this repository for the production images.
Finally, it updates the steps in the README
Fixes #423
=> Use github actions to build images in GHCR and pull from there for deployment

docker-compose.yml
In #454 @rgaudin added an env file that allows us to back up the WP1 database using a docker image running on the production server.
This PR adds that backup image to the production docker-compose file, so that it is automatically run when the WP1 server is deployed.
=> Add backup image to docker-compose

.github/workflows/workflow.yml, db/test/conf.d/test.cnf, db/test/init/01-databases.sql, docker-compose-test.yml, wp1/api.py, wp1/base_db_test.py, wp1/credentials.py.dev.e2e, wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/db_test.py, wp1/environment.py, wp1/storage_test.py, wp1/tables.py, wp1/web/app.py, wp1/web/base_web_testcase.py, wp1/web/oauth.py, wp1/web/projects_test.py, wp1/wiki_db_test.py, wp1/wp10_db_test.py
As explained in #472, unit tests were taking too long on a development machine with local MySQL or MariaDB. This change provides a test database in docker-compose-test.yml that developers can run, which is set up to discard data and have no durability. This makes the tests run much faster.
In acknowledgement that developers might not want to run this test database and may wish to provide their own, this PR also adds a `Environment.TEST` value to the `Environment` enum. The TEST environment contains credentials for the wp10db and the wikidb, but nothing else. This PR also contains updates to additional files that expected credentials.py to be missing in tests.
Overall, this is a good change because it makes the test database configurable (at all, which it wasn't before). It also allows a …
=> Create TEST environment and add docker-compose-test for faster unit tests.

db/README.md, db/migrations/20220813_01_rhr0D-add-current-version-column-to-builders.py, db/migrations/20220813_02_Yqp7y-add-version-column-to-selections.py, db/migrations/20220818_01_5x0T9-add-object-key-column-to-selections.py, docker/dev-db/README.md, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/selection.py, wp1/logic/selection_test.py, wp1/models/wp10/builder.py, wp1/models/wp10/selection.py, wp1/models/wp10/selection_test.py, wp1/selection/abstract_builder.py, wp1/selection/abstract_builder_test.py, wp1/web/builders.py, wp1/web/selection_test.py, wp10_test.up.sql
This is pre-work needed for #432 
We add a `version` column to selections and a `current_version` column to builders. Only selections that match the `current_version` of a builder are displayed in the interface (but see #487).
When a builder is updated and selections are re-materialized, the version increments by one. In the future, the download link will be a redirect to the most recent version.
The builder name is now used as part of the object_key of the selections. We also start storing the `object_key` (the s3-like storage key) of the selection in the database. This allows us to resolve the URL of the selection even when the builder name changes. Previously we were calculating these values on the fly.
This change contains no UI updates, besides returning the proper object_key for …
=> Version builders and selections, and store object_key on selection

openapi.yml, wp1/constants.py, wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/selection.py, wp1/logic/selection_test.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/web/selection_test.py
Fixes #432
Instead of returning URLs that point to the object storage directly, the selection API now returns URLs that point to a new endpoint on the WP1 API server, that 302 redirects to the object storage. See the attached issue for more details.
=> Change selection URL to redirect to latest version

wp1-frontend/src/components/SimpleList.vue, wp1/credentials.py.example, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/selection.py, wp1/logic/selection_test.py, wp1/storage_test.py, wp1/web/builders.py, wp1/web/builders_test.py
This PR provides the infrastructure and frontend (full feature) for deleting builders and any selections associated with them. It will remove the builders and selections from the database and attempt to delete the object keys for the selections from the s3-like storage. Currently the return value of the s3 RPC is not checked and it could fail, with orphaned files being left in s3. Bug #491 tracks fixing this.
There is a bit of confusion around the terminology here. The backend refers to the named entity which defines the blueprint for creating an article list as a "builder", and the materialized list itself which is stored in s3 as a "selection". The frontend refers to the builder as "Simple Selection" and when you save or delete one it says "Save/Delete List". The frontend also conflates …
=> Add support for deleting builders and associated selections

wp1-frontend/src/components/SimpleList.vue, wp1/selection/models/simple_builder.py, wp1/selection/models/simple_builder_test.py
Fixes #435
Allows users to put comments starting with "#" and any whitespace they like in their Simple buiilders. These are ignored at both validation and selection building time.
The result of this is that selections materialized with builders with comments have only the articles and none of the comments/whitespace, but the builders retain that information for the user's use.
=> Comments and whitespace in Simple builders

db/migrations/20220905_01_4yJzk-change-builder-id-column.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/project.py, wp1/logic/project_test.py, wp1/logic/rating.py, wp1/logic/selection_test.py, wp1/models/wp10/builder.py, wp1/models/wp10/rating_test.py, wp1/models/wp10/selection.py, wp1/selection/abstract_builder_test.py, wp1/web/__init__.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/web/projects_test.py, wp1/web/selection_test.py, wp10_test.up.sql
Fixes #501 
The migration generates a new ID for all builders, a UUID. It updates all materialized selections to reference the new ID. This means that old URLs of the form `https://api.wp1.openzim.org/v1/builders/15/selection/latest.tsv` will now be something like `https://api.wp1.openzim.org/v1/builders/e1af5673-3929-4c3c-84c5-63e37369b6db/selection/latest.tsv`, and the old URL will no longer function.
A reverse migration is provided, just in case.
The code and tests have been updated to deal with builder IDs as byte strings.
=> Change builder IDs from monotonically increasing integer primary keys to UUIDs

db/migrations/20220905_01_4yJzk-change-builder-id-column.py
The migration added in the last PR had a bug. In case it needs to be applied to new dev DBs or rolled back and applied again, fix it
=> Retroactively fix broken migration, just in case

requirements.txt, wp1-frontend/cypress/fixtures/sparql_builder.json, wp1-frontend/cypress/integration/updateSparqlList.js, wp1-frontend/src/components/SparqlList.vue, wp1/constants.py, wp1/selection/models/sparql.py, wp1/selection/models/sparql_test.py
Fixes #479 
This PR adds a dependency on [rdflib](https://github.com/RDFLib/rdflib/) to parse SPARQL queries. For initial validation, any query that doesn't parse is sent back to the frontend with a message about parsing errors. Additionally, any query which parses, but contains prefix outside the standard list of Wikidata included prologue PREFIXes (referenced from [here](https://www.wikidata.org/wiki/EntitySchema:E49)) is also rejected.
Once the query has been parsed, it is stored in the enwp10 db with the builder. When it is time for the builder to materialize the query into a list of articles, the query is munged to include a `_wp1_0` variable and a LEFT JOIN (`OPTIONAL`) clause, which selects the article URL based on the token (`queryVariable`) that was selected in the frontend. This …
=> Parse SPARQL queries, and materialize them using Wikidata SPARQL service

wp1/base_db_test.py, wp1/selection/abstract_builder_test.py, wp1/selection/models/simple.py, wp1/selection/models/simple_test.py, wp1/selection/models/sparql.py, wp1/selection/models/sparql_test.py
I didn't write a bug report for this issue, because once I discovered it, I realized it was a p0 in production and immediately started fixing it.
The bug is that Simple builder `build` method was written such that if it didn't have exactly 1 param named `list`, it would throw a ValueError. This is suboptimal, because as we see in #524 it is necessary to pass the project name as a param, generically to all builders. Indeed, there may be cases in the future where new params are necessary to pass down from the AbstractBuilder.
The real problem was the missing tests for SimpleBuilder.materialize and SparqlBuilder.materialize. Although there were tests for those methods in AbstractBuilder, they didn't take into account the specific build methods of the subclass.
This PR fixes the immediate bug …
=> Fix critical bug which doesn't allow Simple builders to be materialized

wp1-frontend/cypress/fixtures/save_sparql_failure.json, wp1-frontend/cypress/fixtures/save_sparql_success.json, wp1-frontend/cypress/integration/createSimpleList.spec.js, wp1-frontend/cypress/integration/createSparqlList.spec.js, wp1-frontend/cypress/integration/updateSimpleList.js, wp1-frontend/cypress/integration/updateSparqlList.js, wp1-frontend/src/components/BaseBuilder.vue, wp1-frontend/src/components/SimpleBuilder.vue, wp1-frontend/src/components/SparqlBuilder.vue, wp1-frontend/src/main.js
When the SPARQL creation/edit page was written, it was copied verbatim from the SimpleList.vue create/edit page. Some changes were made, but the pages stayed basically the same. Now, with fixes for issues such as #521 required, it makes sense to pay off this tech debt and consolidate the two into a single page, with parameters passed by each specific page and callbacks where appropriate.
This has the added benefit that it greatly simplifies the process for someone in the future adding their own Builder module to the app.
=> Refactor Simple and SPARQL create/edit pages to a single component

wp1/logic/rating.py
Fixes #530 and fixes #474 
Pagination was messed up because the query was using a full join between the global rankings table, which meant that the page and article counts were inflated ~5x. This only manifested on the article page listings on the website itself, and didn't affect the counts used when creating tables.
=> Fixes for pagination

db/migrations/20220818_01_5x0T9-add-object-key-column-to-selections.py
The import path for builders changed but the migration was not updated. This means that any migration operations that require importing previous migrations would fail with an `ImportError`. This PR fixes that.
=> Fix migration import

wp1/logic/rating.py
Fixes #474 
I don't know why we never sorted the articles alphabetically. It seems obvious, and should help maintain a stable sort order.
=> Order articles alphabetically in lists

wp1/custom_tables/us_roads.py, wp1/custom_tables/us_roads_test.py
Calculation of omega was wrong based on comment; https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index#Custom_table_updates
=> Fix omega calculation for US Roads

wp1-frontend/src/components/MyLists.vue
The list item is considered pending if the Builder has been updated more recently than the Selection.
Fixes #522.
=> Use spinner for Builder items that still need Selection update

wp1/selection/models/sparql.py, wp1/selection/models/sparql_test.py
Fixes #523.
It's not actually necessary to check that the query variable appears in the `SELECT`, because we don't need to select it. As long as it is bound to something in the `WHERE` clause, we can join with it's article URLs, which is what we're actually after.
=> Check for the query variable in the given SPARQL

wp1-frontend/vite.config.js
In the previous PR (#540), the config for production was broken. The config for dev worked fine and the integration tests passed against that version. And while the frontend-build test passed and the app could build for production, the actual app was broken.
This PR fixes it, but we should look into having the Cypress integration tests run against a production build of the app, so that issues like this can be caught sooner.
=> Fix config for prod jquery

wp1/logic/builder.py, wp1/logic/builder_test.py
The database schema for selections makes 'OK' the default value. However some of the builder code was written assuming NULL was the default for selections with no errors. This PR fixes that.
=> Fix status selection for builders, default is OK

wp1-frontend/src/components/MyLists.vue
The frontend additionally had a bug where it was only checking for non-NULL status as indication of error. Whereas in production, the status could be 'OK' to indicate success. See #550
=> Additional status bug on frontend

wp1-frontend/src/components/SparqlBuilder.vue
Fixes #554
Just split on the anchor tag in order to allow URLs where the path is not exactly `/` or `/index.html`.
=> Less specific URL splitting for SPARQL URL input

wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/selection/models/sparql.py
Fixes #555.
As explained in #555, that specific query was causing confusing results because the query variable was wrong. In general though, we need to be resilient against the possibility of there being no results in response from Wikidata. For this purpose, an empty results set is now considered a "fatal" error, since it couldn't be fixed by simply retrying and the query itself (or in this case the query variable) needs to be edited.
=> Raise error if SPARQL query results are non-error but empty

wp1-frontend/src/components/BaseBuilder.vue, wp1-frontend/src/components/SimpleBuilder.vue, wp1-frontend/src/components/SparqlBuilder.vue
As a workaround to component reuse, this PR adds a `:key="$route.path"` to affected components. This is intended to cause them to be discarded by the Vue renderer when the route changes. While this fixes the 404 error seen in #570, it doesn't fully resolve the issue because the contents of the form fields are preserved after the route change.
=> Attempt to fix routing issues. Doesn't quite work.

wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/exceptions.py, wp1/logic/builder.py, wp1/logic/selection.py, wp1/logic/util.py, wp1/logic/util_test.py, wp1/selection/abstract_builder_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py
This PR is part of #483. It provides the backend API for:
1. Connecting to a Zimfarm instance as configured in credentials.py, using user name and password and storing `access_token` and `refresh_token` in Redis
2. Requesting a ZIM file creation task from the Zimfarm based on a specific Builder, using it's latest selection that is in TSV format
Currently, this is "fire and forget". The library does not monitor the requested task or provide for any way, in WP1, to find out its status or download the resulting ZIM file.
It is also standalone and not called from anywhere in WP1.
Future work will first integrate this functionality with the web API at api.wp1.openzim.org, so that there is a way to request ZIM files based on WP1 Builders. As part of that, we will create a job tracking system so …
=> Create zimfarm.py module for getting Zimfarm access tokens and requesting ZIM file creation tasks

db/migrations/20230316_01_eMzhU-create-zimfarm-fields-on-selections.py, docker-compose-dev.yml, docker/dev-workers/Dockerfile, requirements.txt, supervisord-dev.conf, supervisord.conf, wp1/credentials.py.dev.example, wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/custom_tables/us_roads_test.py, wp1/exceptions.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/selection.py, wp1/logic/selection_test.py, wp1/models/wp10/selection.py, wp1/queues.py, wp1/queues_test.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/web/selection_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py, wp10_test.up.sql
This PR adds an API endpoint for scheduling ZIM file creation. The endpoint currently takes no arguments, though once there is a UI it will take a description and long_description. The API immediately calls `zimfarm.schedule_zim_file`, and if that method raises any exceptions, the appropriate status code is sent back to the client. Specifically, if a generic `ZimFarmError` occurs, which indicates that there was some kind of problem (400 or 500) communicating with the Zimfarm, a detailed error message is returned alongside the user-friendly one, to better help with debugging.
This PR also adds a webhook so that the Zimfarm can notify the WP1 instance when the task is 'ended'. The webhook is trivially secured with a token in `credentials.py` that the Zimfarm server sends back to the WP1 …
=> Create API endpoint for scheduling ZIM file creation

docker-compose.yml
docker.io hosted image has been removed already and any new pull would fail. This image is now available on ghcr.io
=> Use borg-backup image from ghcr.io

db/migrations/20230326_01_hOgak-add-zim-file-updated-at-to-selections.py, db/migrations/20230326_02_bTYKT-remove-default-for-s-zimfarm-status.py, wp1-frontend/cypress/e2e/myLists.cy.js, wp1-frontend/cypress/e2e/zimFile.cy.js, wp1-frontend/cypress/fixtures/list_data.json, wp1-frontend/cypress/fixtures/zim_status_not_ready.json, wp1-frontend/cypress/fixtures/zim_status_not_requested.json, wp1-frontend/cypress/fixtures/zim_status_ready.json, wp1-frontend/src/components/BaseBuilder.vue, wp1-frontend/src/components/CreateZimFile.vue, wp1-frontend/src/components/MyLists.vue, wp1-frontend/src/components/SparqlBuilder.vue, wp1-frontend/src/components/ZimFile.vue, wp1-frontend/src/main.js, wp1/credentials.py.dev.example, wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/selection.py, wp1/logic/selection_test.py, wp1/models/wp10/selection.py, wp1/models/wp10/selection_test.py, wp1/selection/models/sparql.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/web/selection_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py, wp10_test.up.sql
This PR provides the frontend UI, written in Vue, to allow a user to create a ZIM file from their WP1 Selections. It provides a new page where the user can enter the `Description` and `LongDescription` of the ZIM file, request its creation, monitor its progress, and download the ZIM file when it is ready. The ZIM file also has an updated time which is displayed in the 'My Selections' table view, where the ZIM file can also be downloaded.
Fixes #484. Fixes #483. Fixes #482. Fixes #481.
=> UI for requesting ZIM file for WP1 Selection

wp1-frontend/cypress/e2e/myLists.cy.js, wp1-frontend/cypress/e2e/zimFile.cy.js, wp1-frontend/cypress/fixtures/list_data.json, wp1-frontend/cypress/fixtures/zim_status_failed.json, wp1-frontend/src/components/MyLists.vue, wp1-frontend/src/components/ZimFile.vue, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py
Fixes #604.
Check for `status: failed` in the JSON returned by the Zimfarm, both when the webhook is called and when polling for file ready status. If a failure state is detected in either case, mark the Selection Zim status as `FAILED`.
When this status is encountered in the frontend, display a failure message with an option to retry. Also display failed status in the My Lists table with an option to go to the Zim file page and retry.
=> Deal with ZIM file errors on the Zimfarm

db/migrations/20230427_01_QJ8ZK-add-zim-file-table.py, db/migrations/20230427_02_Sareg-drop-selections-zim-file-fields.py, db/migrations/20230429_01_e8yCB-add-zim-file-versions.py, db/migrations/20230513_01_4PsR6-add-descriptions-to-zim-file-table.py, wp1-frontend/cypress/fixtures/list_data.json, wp1-frontend/src/components/MyLists.vue, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/selection.py, wp1/logic/selection_test.py, wp1/models/wp10/selection.py, wp1/models/wp10/selection_test.py, wp1/models/wp10/zim_file.py, wp1/models/wp10/zim_file_test.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/web/selection_test.py, wp10_test.down.sql, wp10_test.up.sql
Fixes #612.
This is mostly a refactor in preparation for #581. We need to have a separate ZIM file table, since the old file needs to be retained while the new one is auto-generated. We also need to keep track of the `description` and `long_description` of the ZIM file so that we can automatically re-request it without re-prompting the user.
This PR adds no new features and the migrations are designed so that everything already in place keeps working.
=> Re-factor ZIM files to their own table

wp1/logic/builder.py, wp1/logic/builder_test.py
In the previous PR, the values for `description` and `long_description` were swapped. This fixes it and adds a test.
=> Fix swapped values and add test

.github/workflows/ci.yml, docker-compose-dev.yml, docker-compose-test.yml
By default, the "name" of the docker graph created by docker-compose is the same as the directory in which the files are run from. This means that when running`docker-compose up -f docker-compose-dev.yml` and running `docker-compose up -f docker-compose-test.yml`, they both get the same project name. This causes a conflict between the `redis` image in each.
This change adds a name field to each compose file, so the graphs run under different 'projects' and no longer conflict.
=> Add name to docker compose files

db/migrations/20230528_01_cSwUS-remove-selection-and-zim-file-versions.py, db/migrations/20230528_02_pL6ka-add-b-selection-zim-version-to-builders.py, wp1-frontend/cypress/e2e/myLists.cy.js, wp1-frontend/cypress/fixtures/list_data.json, wp1-frontend/src/components/MyLists.vue, wp1-frontend/src/components/ZimFile.vue, wp1/credentials.py.dev.example, wp1/credentials.py.e2e, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/selection.py, wp1/logic/selection_test.py, wp1/models/wp10/builder.py, wp1/models/wp10/selection.py, wp1/models/wp10/zim_file.py, wp1/selection/abstract_builder.py, wp1/selection/abstract_builder_test.py, wp1/selection/models/simple_test.py, wp1/selection/models/sparql_test.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/web/selection_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py, wp10_test.up.sql
Fixes #581.
This PR follows the requirements outlined in #581. When a user updates their selection, and they have already requested a ZIM file, a new ZIM file is requested for them automatically. The Selections list (`MyLists.vue`) will show the outdated ZIM file in warning orange with a tooltip that informs the user that the ZIM is outdated and a new one has been requested. Note that no new ZIM is requested if there wasn't an existing ZIM file. Once the new ZIM file is ready (via the same webhook/polling as before), the Builder for that Selection/ZIM is updated and the new ZIM file displays in the UI. There is also polling added (every 5 minutes) for outdated ZIM file, so if the user comes back to the page they will see the new file when it is ready (no spinner though).
As far as the …
=> Automatically update ZIM files when the Selection is updated

wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py
Fixes #622.
Here, we check for any ZIM file objects in the database for the given builder that are in the REQUESTED state, when auto-queueing a new ZIM file. That way, we can cancel these pending tasks before queueing the new ZIM file for creation. This prevents the race condition described in the bug.
=> Cancel outdated ZIM tasks when a new ZIM is auto-updated

wp1-frontend/cypress/e2e/myLists.cy.js, wp1-frontend/cypress/fixtures/list_data.json, wp1-frontend/src/components/MyLists.vue, wp1/constants.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/web/selection_test.py
Fixes #634.
Although the technical fix for that issue was to just fix the millisecond conversion so that ZIM updated dates were calculated properly, it proved impossible to test that solution with Cypress (see the issue).
Here, we calculate the deletion status of the ZIM file on the server, so that it doesn't depend on a client `now()` value. This allows us to more easily test it in the frontend.
=> Fix bug with deleted ZIMs in UI

requirements.txt, wp1-frontend/src/components/PetscanBuilder.vue, wp1-frontend/src/components/SecondaryNav.vue, wp1-frontend/src/main.js, wp1/selection/models/petscan.py, wp1/selection/models/petscan_test.py, wp1/web/builders.py
[Petscan](https://petscan.wmflabs.org/) allows for powerful methods for selecting articles based on union or intersection of categories, among other features. Particularly notable is the fact that for a category such as `Living_people`, which has over a million results, Petscan is able to generate the article list. It is dubious if our SPARQL Builder would be able to create such a list.
This PR implements a Petscan Builder, as well as a frontend that allows for Petscan selection based on URL.
=> Allow for Selection based on Petscan URL

wp1-frontend/cypress/e2e/zimFile.cy.js, wp1-frontend/cypress/fixtures/zim_status_deleted.json, wp1-frontend/cypress/fixtures/zim_status_failed.json, wp1-frontend/cypress/fixtures/zim_status_not_requested.json, wp1-frontend/cypress/fixtures/zim_status_ready.json, wp1-frontend/src/components/ZimFile.vue, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/selection.py, wp1/web/builders.py, wp1/web/builders_test.py
Fixes #637
This change passes the `is_deleted` flag to the ZIM creation page. If it sees that value, it notifies the user that their ZIM has expired and allows them to re-request.
=> Update ZIM page to allow re-requesting ZIM files that have expired

wp1-frontend/src/components/BookBuilder.vue, wp1-frontend/src/components/SecondaryNav.vue, wp1-frontend/src/main.js, wp1/selection/models/book.py, wp1/selection/models/book_test.py
Fixes #644.
Users can create selections based on a Wikipedia "book" url, such as https://en.wikipedia.org/wiki/User:Audiodude/Books/test. The Book Builder fetches the wikitext of the page that is saved by this tool and parses out the article names, then saves them in S3. A frontend is provided for creation of Book selections, which verifies that the URL is present, valid, and matches the project selected in the dropdown.
Book selections can be used to create ZIM files just like any other selection.
=> Allow users to create selections from Wikipedia books

requirements.txt
This was included in the main `requirements.txt`, probably as mkdocs was being developed, but is not needed there.
=> Remove mkdocs from main requirements.txt

Pipfile, Pipfile.lock
It is needed for the workers image, but was overlooked in the migration to Pipfile.
=> Re-add supervisor

.github/workflows/ci.yml, .tool-versions, Pipfile, Pipfile.lock, README.md, docker/workers/Dockerfile
We have spent some time putting various pieces of the code under Python 3.12, but it wasn't all together yet. Specifically, when moving to Pipfile (#685), we went back to Python 3.9.4 temporarily so that we would have an agreed upon starting place for rebuilding the dependency library.
This PR moves everything to Python 3.12.0. All Python tests pass, so I feel confident this is working.
=> Consolidate all code under Python 3.12.0

wp1-frontend/cypress/e2e/myLists.cy.js, wp1-frontend/src/components/MyLists.vue
This time, we set the default datatables view to 25 entries, so we don't have to change it in the Cypress test, which was flaky.
=> Another attempt at fixing flaky cypress tests

Pipfile, Pipfile.lock
The `yoyo-migrations` package was defined as part of the dev packages, which means it wasn't being installed in the production images. This means it would be impossible to run the migrations in prod as part of the deployment steps.
=> Move yoyo to prod packages, so migrations can be run in prod

wp1/selection/models/simple.py, wp1/selection/models/simple_test.py
Fixes #717. Fixes #719.
This is because the validation results already strip comments and url decode, and invalid lists should not be allowed to be built anyway.
=> Use validation results for building Simple Selections

wp1/logic/builder.py, wp1/selection/abstract_builder.py, wp1/selection/models/wikiproject.py, wp1/selection/models/wikiproject_test.py, wp1/web/builders.py
In WP1, we have the concept of a Builder, which is a sort of module that knows how to "build" selections from various data sources and parameters. For example, the Simple builder takes a `list=['Article 1', 'Article 2', ...]` parameter and does some validation before echoing back the list as a selection. The SPARQL Builder sends a SPARQL query to the Wikidata API and formats the response into a selection.
Note that in the codebase, "builder" is also the name given to a user's specific instance of a Builder, with the parameters instantiated and saved in the database.
In this PR, we introduce the WikiProject Builder, to create a selection based on the articles that are part of one or more WikiProjects. WP1 already has a mapping of WikiProjects -> articles, based on the work of the WP1.0 …
=> Add WikiProject Builder model, only in Python not exposed to frontend yet

wp1-frontend/cypress/e2e/createWikiProjectList.cy.js, wp1-frontend/cypress/e2e/updateWikiProjectList.cy.js, wp1-frontend/cypress/fixtures/save_wikiproject_failure.json, wp1-frontend/cypress/fixtures/wikiproject_builder.json, wp1-frontend/cypress/fixtures/wikiproject_builder_fatal_error.json, wp1-frontend/cypress/fixtures/wikiproject_builder_retryable_error.json, wp1-frontend/src/components/BaseBuilder.vue, wp1-frontend/src/components/BookBuilder.vue, wp1-frontend/src/components/PetscanBuilder.vue, wp1-frontend/src/components/SecondaryNav.vue, wp1-frontend/src/components/SimpleBuilder.vue, wp1-frontend/src/components/SparqlBuilder.vue, wp1-frontend/src/components/WikiProjectBuilder.vue, wp1-frontend/src/main.js
The WP1 frontend is written in Vue js (version 2). We have created a component, which essentially acts as a standalone "page", for each type of Builder. The component for each Builder handles both create/update. Conceptually, the individual Builder components "inherit from" the BaseBuilder.vue, though the mechanism is actually more like parameterization.
The WP1 API, which corresponds to Python functions in wp1.web, operates on instances of Builders generically. Similar to how the backend Python code works, builders simply have a list of properties that are common to all of them, with the `params` key in the request/response JSON varying.
The BaseBuilder handles concerns that are common to all Builder components, like providing instruction text, allowing the user to select a Wikimedia …
=> Frontend for WikiProject Builder

Pipfile, Pipfile.lock, wp1/credentials.py.example, wp1/db.py, wp1/db_test.py, wp1/wiki_db.py, wp1/wikilang_db.py, wp1/wikilang_db_test.py
Previously, the development environment only needed to connect to the English wikipedia replica database, so it was enough to set up a ssh tunnel and connect through that. However, in future versions of the code, we will need to connect to a variety of wiki replica database, in order to select `links` and `lang_links`. So, for example, for French wikipedia, we will need to connect to `frwiki.analytics.db.svc.wikimedia.cloud`. In fact, we will need to connect to all db replicas for all wikipedia languages.
This code will not be used in production, it is only for development. In production, the `*.analytics.db.svc.wikimedia.cloud` hosts are all reachable from the production cloud VPS server. For local testing and debugging, we need the SOCKS proxy.
=> Set up db connections to use SOCKS proxy in Development environment

db/migrations/20240429_01_qtSms-add-scores-table.py, docker-compose.yml, docker/dev-db/README.md, wp1/credentials.py.dev.e2e, wp1/credentials.py.e2e, wp1/credentials.py.example, wp1/exceptions.py, wp1/scores.py, wp1/scores_test.py, wp10_test.down.sql, wp10_test.up.sql
For #171 
Here we download the pageviews text file for the previous month and ingest it, storing the view counts for every article, across every wikipedia, that has a view count.
This PR includes the schema for the `page_scores` table, which will eventually include more than just the page views, also the links and lang_links that make up the components of the page score used in classic selection.
Previous attempts at this logic involved streaming the pageviews bz2 file over HTTP, however this was found to be unreliable because the remote server would close the connection after ~20 minutes. Instead, we create a tempfile location, which in production is mapped to /srv/, and download the entire file there. The BZ2 decompression and line by line processing is still streamed.
EDIT: There is …
=> Calculate pageviews for all articles across all wikipedias

wp1/web/builders.py
Fixes #780 
See https://phabricator.wikimedia.org/T382139
The Mediawiki oauth integration was recently updated to return a string for the "sub" field instead of an int. Since MW is the only OAuth provider we integrate with, we have always stored this field as an int in the database. After this change went live, users that logged out and logged in again were getting 401 errors (which get downgraded to 404 in the UI) because the value is an int in the database but was a string in their session.
=> Use string coercion to compare user ids

db/migrations/20250120_01_4GEMs-convert-user-id-to-str.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/web/builders_test.py, wp10_test.up.sql
Fixes #784. Related to #783. Related to #780.
Fix an additional place in the codebase where we compare user IDs for access control. User IDs from wikimedia OAuth endpoints are now strings instead of ints.
To accommodate this change and hopefully avoid this issue in the future, we now map the user IDs to VARCHAR (strings) in the database.
However there is still a small issue in that user_ids coming from the database will be bytes (`b'1234'`) and ones from the session will be str (`'1234'`), so care still has to be taken when comparing them.
=> Migrate database user IDs to strings, and compare as strings

wp1/selection/models/wikiproject.py, wp1/selection/models/wikiproject_test.py
Fixes #788
Originally, WikiProject selection grabbed every `r_article` from the ratings table for the project. However, many items in the table are not proper articles (namespace == 0) but rather things like categories etc. This caused problems for mwoffliner because it couldn't download those, which led to failed ZIMs.
=> Limit WikiProject selection to article namespace

wp1/selection/models/simple.py, wp1/selection/models/simple_test.py
Fixes: #721 
This PR updates the Simple Selection validator to dynamically strip Wikipedia article URLs based on the project name instead of hardcoding `en.wikipedia.org`. This allows the validator to support non-English Wikipedia projects (e.g., `fr.wikipedia.org`, `de.wikipedia.org`, etc.).
Related Issues
=> feat: extend URL stripping to support non-EN Wikipedia projects

wp1/base_db_test.py, wp1/logic/log.py, wp1/logic/page.py, wp1/logic/page_test.py, wp1/logic/project.py, wp1/logic/project_test.py, wp1/logic/rating.py, wp1/logic/rating_test.py, wp1/logs.py, wp1/logs_test.py, wp1/models/wp10/log_test.py, wp1/queues_test.py, wp1/redis_db.py
This PR implements the functionality to save logs to Redis. By setting expiry on the logs while saving, we can be sure that logs are not saved for years and there is no need for reliance on a cron job to delete old logs.
- set up connection to Redis in `BaseWPOneDbTest`
- save logs to Redis as hashes instead of SQL DB
- use a key naming pattern which allows us to filter logs that match the pattern. This emulates SQL-like `AND` queries for logs
- update tests to use appropriate `self.redis` 
This fixes #778 
This fixes #49
=> refactor: store logs as Redis hashes

wp1-frontend/src/components/ArticleTable.vue, wp1/web/articles.py, wp1/web/articles_test.py
Fixes #817 
In frontend, double encode the article name.
In backend, decode the encoded article name (Flask decode the first time, and we decode it the second time to get original name).
=> Fix broken link bug for article's name that includes slash

enqueue-all.py, enqueue-global.py, wp1/api.py, wp1/base_db_test.py, wp1/conf.py, wp1/credentials.py.e2e, wp1/db.py, wp1/logic/selection.py, wp1/queues.py, wp1/redis_db.py, wp1/scores.py, wp1/storage.py, wp1/storage_test.py, wp1/tables.py, wp1/web/__init__.py, wp1/web/app.py, wp1/web/dev/projects.py, wp1/web/oauth.py, wp1/web/redis.py
Remove redundant `ImportError` since there is always a `credentials.py`. This fixes #486
=> remove redundant ImportErrors

wp1/logic/selection.py
Fix that solves problems reaching s3 when there is a '/' at the end of the S3_PUBLIC_URL.
While working on #834 I found a bug: If there's a '/' at the end of the s3 endpoint url the generated file url will be something like this: https://example.com//path/to/file which will of course result in files not found or errors on the s3 endpoints.
This small change fixes it. :)
=> fix: URL generation by stripping trailing slashes from S3_PUBLIC_URL

docker-compose-dev.yml, docker/minio/setup-buckets.sh, wp1/credentials.py.dev.example, wp1/credentials.py.example
I added two new containers in docker-compose-dev.yml, one to run MinIO, and one to setup buckets in it.
I used the default docker images minio/minio to run MinIO and minio/mc to setup the buckets (with a script to do that in a clean way).
I create only a org-kiwix-dev-wp1 bucket in the script. 
On [localhost:9001](http://localhost:9001) there's also the MinIO web console available to easily check uploaded files in buckets.
I also added default credential for MinIO in credentials.* and updated comments on those files.
I tested it locally and it works: I am able to download the .tsv files.
Solves #832, and will make the setup for development of WP1 a bit easier. :)
=> #832: Include Minio in docker-compose-dev.yml

wp1/credentials.py.dev.example, wp1/credentials.py.example
Small changes to the credentials example files:
- Fixed docker-compose command in `credentials.py.example`
- Added a missing comma  in `credentials.py.dev.example`
- Corrected redis port in `credentials.py.dev.example`
I've tested the change of the redis port by opening a connection inside the container and it works correctly.
(it also makes sense give the docker-compose):
```yaml
redis:
image: redis
container_name: wp1bot-redis-dev
ports:
- '9736:6379'
networks:
- wp1bot-dev
restart: always
```
=> fix: correct Redis port and improve example instructions in credentials files

db/migrations/20250325_01_sFddz-add-article-count-to-selection-table.py
There was a bug in the original migration that shipped with #818, in that we didn't expect `NULL` values for `s_object_key` in the `selections` table, but some values existed. This caused the migration to fail.
To continue the deployment, we temporarily edited the migration file in the running container in order to add these lines. The migration completed successfully and now we are retroactively adding this line to the repo for historical reasons.
=> Fix bug in migration to handle NULL/empty object ids

wp1-frontend/cypress/e2e/createWikiProjectList.cy.js, wp1-frontend/cypress/e2e/updateWikiProjectList.cy.js, wp1-frontend/cypress/fixtures/save_wikiproject_failure.json, wp1-frontend/src/components/Autocomplete.vue, wp1-frontend/src/components/WikiProjectBuilder.vue
Fixes #775
I tried implementing something like what is proposed in #775. I reused the Autocomplete component from the Project home page and did some modifications to make it work correctly (especially to get errors and so on).
I used bootstrap for the style.
I modified the unit tests (although I was not able to test them all correctly cause the Autocomplete is not working properly when I run tests locally (but it works in my local deployment)). I will for sure continue working on the unit tests part :)
Hope to have your feedback. :)
Here's a screenshot of the modified page:
=> feat: enhance WikiProject builder with autocomplete for project selection

docker-compose-dev.yml, docker-compose.yml
By defining a healthcheck for the redis db and ensuring the services that depend on it wait for the healthchek to pass, services that rely on it can avoid crashing on startup as redis might not be ready.
This fixes #836
=> wait for redisdb to start

wp1-frontend/.env.development
As described in #841, unit tests are not working properly in the local development environment. 
In particular, I was not able to use the autocomplete component properly during test with cypress. 
Debugging I found out that inside cypress test environment I was not able to reach `localhost:5000/v1`.
Changing from the `VITE_API_URL` to use `127.0.0.1` instead of `localhost` in file `.env.development` solves the issue.
=> fix: update VITE_API_URL to use 127.0.0.1 instead of localhost in .env.development

rate_limit_queue.py
We recently upgraded to rq 2.2.0, however this introduced API changes. The worker jobs broke in production and it was difficult to tell why.
The root cause was that `dequeue_any` method is now expected to take an additional `death_penalty_class` keyword argument.
We've tried to future proof the RateLimitQueue in this class a bit by using `*args` and `**kwargs`, because we don't need to operate on any of them and just want to pass them to the `super().dequeue_any()` method.
=> Update custom RateLimitQueue rq class to take **kwargs for forward compatibility

docker/dev-db/enwp10_dev.dump.sql
The dev db was not up to date with the latest migrations, resulting in problems with the latest changes.
To fix the dev. env, I applied the following migrations that were missing:
- [20250323_01_xyzAB-add-temp-pageviews-table]
- [20250324_02_arj6b-add-ps-article-index-to-page-scores]
- [20250330_01_zaRQa-migrate-last-7-days-of-logs]
- [20250325_01_sFddz-add-article-count-to-selection-table]
=> chore: update dev db with new migrations

README.md, wp1-frontend/.env.development
In #843, the VITE_API_URL was changed from `localhost` to `127.0.0.1`. This causes problems with auth in the development environment, since the frontend loads `http://127.0.0.1/v1/oauth/initiate` but the callback from the Wikimedia OAuth API is `http://localhost:5000/v1/oauth/complete`. Because of the mismatch, the session cookies don't match up, the browser sees `127.0.0.1` and `localhost` as different hosts, and as such sends different cookies (which then corresponds to different Flask sessions).
It's not completely clear what the actual issue is that causes cypress to be unable to contact the Flask backend in e2e tests. It's likely something to do with the networking config on the host machine, and has nothing to do with any application code. I've had similar issues with my mac, and …
=> Restore VITE_API_URL to localhost to fix auth issues

Pipfile, Pipfile.lock, wp1-frontend/cypress/e2e/zimFile.cy.js, wp1-frontend/package.json, wp1-frontend/src/components/ZimFile.vue, wp1-frontend/yarn.lock, wp1/exceptions.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py
Fixes #677 
I added a `Title` field in the Zim creation page. This field is automatically filled with the `Selection Title` reduced to 30 characters. In this way users can change it if they want. This field is required and is of max 30 chars. (I also added a char counter for both the title and the description).
I also added backend validation for the size of zim metadata (title (30) and description (80) as per https://wiki.openzim.org/wiki/Metadata).
I added new unit test for the new "title field" and the validation, for both the backend and the frontend. I also fixed some unit tests and functions to support the new `zimtitle` field.
Here is the Zim creation page with the new field:
=> feat: add title field and metadata handling for ZIM file creation

wp1-frontend/cypress/e2e/zimFile.cy.js, wp1-frontend/src/components/ZimFile.vue, wp1/exceptions.py, wp1/logic/builder.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py
Fixes #816 
This PR includes both backend limits as well as frontend validation and messaging. The article limit is configured in a single place and passed to the frontend in the same request that provides the number of articles to the ZIM request page. Even if this request is tampered with, or if a request is made through the WP1 API, the backend zimfarm module checks the limits before requesting a ZIM.
=> Limit the number of articles that can be made into a ZIM file

db/migrations/20250426_01_i656U-drop-logging-table.py, wp1/logic/rating_test.py, wp10_test.down.sql, wp10_test.up.sql
Fixes #828 
We have simply added a migration to drop the logging table, and updated the test schemas.
This will save 6 GB in the database and the corresponding amount for every database backup:
```
MariaDB [enwp10_prod]> SELECT      table_name AS `Table`,      round(((data_length + index_length) / 1024 / 1024), 2) `Size in MB`  FROM information_schema.TABLES  WHERE table_schema = "enwp10_prod"
AND table_name = "logging";
+---------+------------+
| Table   | Size in MB |
+---------+------------+
| logging |    5929.91 |
+---------+------------+
1 row in set (0.020 sec)
```
The `Log` model is retained, because it is still used in the Redis version of the code.
I have confirmed that logs have been successfully running off Redis for several weeks now.
Thank you again @elfkuzco!
=> Delete logging table

wp1/logic/project.py, wp1/logic/project_test.py
See discussion at https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Version_1.0_Editorial_Team/Index&oldid=1290492282
It seems like there may have been issues with either database connectivity or correctness, and the bot received an empty list of articles for almost every project. This meant that when it went to `process_unseen_articles()`, it marked every single rating as `NOT_A_CLASS`. This then led to them all being removed from the database and all of the on wiki pages being updated to empty tables. Also, almost all of the log pages were "too big to upload" because they listed "SoAndSoArticle went from A-Class to DELETED" or something similar.
This PR attempts to put a sane failsafe in place. If we haven't "seen" any articles, abort the process of trying to process the unseen …
=> Add failsafe to not update ratings if none have been seen

db/migrations/20250610_01_kNsXy-add-email-to-users-table.py, db/migrations/20250610_02_FHB8A-create-zim-schedules-table.py, docker/dev-db/enwp10_dev.dump.sql, wp10_test.down.sql, wp10_test.up.sql
This PR introduces the new `zim_schedules` table to support scheduled ZIM generation. Changes include:
- A new migration (`20250610_02_FHB8A-create-zim-schedules-table.py`) that creates the `zim_schedules` table with the following fields:
- `s_id`: Primary key (UUID)
- `s_builder_id`: References a builder
- `s_zim_file_id`: Optionally links to the latest ZIM file
- `s_rq_job_id`: Scheduler job ID (from rq-scheduler)
- `s_last_updated_at`: Binary timestamp of last update
- A preceding migration (`20250610_01_kNsXy-add-email-to-users-table.py`) that adds a nullable `u_email` column to the users table.
- Updates to the dev/test SQL dump files (`enwp10_dev.dump.sql`, `wp10_test.up.sql`, `wp10_test.down.sql`) to reflect the schema changes.
These changes prepare the database for handling …
=> feat: add zim_schedules table, migration script and update dump

wp1/models/wp10/zim_schedule.py, wp1/models/wp10/zim_schedule_test.py
This PR introduces the `ZimSchedule` model, representing entries in the `zim_schedules` database table. 
It includes unit tests (`wp1/models/wp10/zim_schedule_test.py`).
Typing added for clarity and improved development experience (e.g., IDE support, static analysis)
Fixes #906
=> Add `zim_schedule` model class

wp1/logic/zim_schedules.py, wp1/logic/zim_schedules_test.py
**add `ZimSchedule` DB logic and corresponding tests**
This PR introduces the core logic for interacting with the `zim_schedules` table, enabling creation, retrieval, updating, and management of `ZimSchedule `records. It also adds comprehensive unit tests to ensure correctness.
added:
- `insert_zim_schedule()`: Inserts a new schedule into the DB.
- `update_zim_schedule()`: Updates an existing schedule’s metadata (e.g., interval, remaining generations).
- `get_zim_schedule()`: Retrieves a schedule by ID.
- `list_zim_schedules_for_builder()`: Lists all schedules for a given builder.
- `decrement_remaining_generations()`: Decreases `s_remaining_generations` by 1 (minimum 0), also updates timestamp.
- `get_scheduled_zimfarm_task_from_taskid()`: Looks up a schedule by associated ZIM file's …
=> add ZimSchedule DB logic and corresponding tests

wp1/logic/builder.py, wp1/web/builders.py, wp1/web/builders_test.py
Introduce the ability to schedule repeated ZIM file generations directly from the `create_zim_file_for_builder()` endpoint.
- Extended `create_zim_file_for_builder()` to accept a `scheduled_repetitions` field from the request body.
- Added input validation to ensure `scheduled_repetitions` includes the required fields:
- `repetition_period_in_months`
- `number_of_repetitions`
- `email`
- Passed the validated `scheduled_repetitions` to `handle_zim_generation()`.
- Updated `handle_zim_generation()` function signature to include the new optional parameter.
Fixes #912
=> Modify `builders.py` api for scheduled zim generations support

wp1/web/oauth.py, wp1/web/oauth_test.py
This PR enhances the OAuth `complete()` flow by ensuring that the user's email is properly retrieved and stored.
If the identity object from the OAuth provider includes an email, it is used directly.
If not, the email is fetched from the users table using the user ID.
The email is then stored in both the session and the users table.
Added also `test_complete_sets_email_in_session()` to verify that the email is correctly set in the session after a successful OAuth flow.
Fixes #916 (wikimedia oauth consumer needs to be updated/recreated with email permissions)
=> add email handling in OAuth complete flow and corresponding test

db/migrations/20220818_01_5x0T9-add-object-key-column-to-selections.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/queues.py, wp1/queues_test.py, wp1/web/builders.py
This PR refactors zim file generation by decoupling `request_zim_file_for_builder()` from `handle_zim_generation()`, and creating a new `request_scheduled_zim_file_for_builder`.
The main reason for this change is to make the zim file request logic flexible for use in scheduled workers.
The new `request_scheduled_zim_file_for_builder()` now handles:
- skipping `user_id` checks, as these are not relevant for scheduled tasks
- re-opening db, redis and s3 connections independently
- rebuilding selections
- initiating the zimfarm request and updating the zim file status
Also a new `materialize_builder_with_connections()` has been added to skip repeated connections and clean the materialize process.
New tests have been added.
Fixes #928
=> Refactor `logic/builder.py:handle_zim_generation()` to be used in scheduled workers

wp1/zimfarm.py, wp1/zimfarm_test.py
Refactor schedule name and zimfile name generation.
Use latest selection from api when creating ZIMFARM schedules.
Fixes #947
=> Use latest selection when creating zimfarm schedules

wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/web/builders_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py
Associate ZIMFARM schedules with builder instead of selection, so that the zimfarm schedule can be re-used with the latest materialized selection.
Fixes #952
=> Associate zimfarm schedule with builder

wp1/constants.py, wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/zim_schedules.py, wp1/logic/zim_schedules_test.py, wp1/models/wp10/zim_schedule.py, wp1/queues.py, wp1/queues_test.py, wp1/web/builders.py, wp1/web/builders_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py
- Added a new function `schedule_future_zimfile_generations()` in `queues.py that:
- calculates next first future xim generation run and interval in months (1 month=30days)
- schedules future zim-generations
- inserts schedule in the DB
- Added call to `schedule_future_zimfile_generations()` function in `handle_zim_generations()`
- Added tests
Fixes #911
=> Implement scheduling for future ZIM file generations

wp1/logic/builder.py, wp1/logic/builder_test.py, wp1/logic/zim_schedules.py, wp1/logic/zim_schedules_test.py, wp1/web/builders_test.py, wp1/zimfarm.py, wp1/zimfarm_test.py, wp10_test.up.sql
This PR adds functionality to re-use zim schedules, updating or creating new ones depending if the exists in the zimfarm or are already used.
Fixes #964 (ZIM schedule migration: check for schedule when requesting manual ZIM)
the zimfile schedule name is changed to not use the builder id so that more then 1 schedule can be created per builder (manual + scheduled)
=> Reuse zim schedules
